### ISSUE TITLE
Working in GeoNetwork 3.8?

### ISSUE THREAD

**Issue by archaeogeek** [metadata101/dcat-ap1.1#2]
Hi,

I've tried to load this in GeoNetwork 3.8 without much success- but it's possible my workflow was incorrect:

- I loaded the master branch as a submodule and added the dependencies to schemas/pom.xml and web/pom.xml. 
- I tried to build without adding the patches and it failed (I think because of the version in dcat-ap/pom.xml)
- I changed the version from 3.5 to 3.7 and it failed again so I added the patches, most of which failed (so I skipped them)
- I built it again and it still failed because of the version, so I changed that back to 3.5, but it still failed.

I completely appreciate that none of this is standard, so really this is just a question about whether anyone has it working in 3.8 or not, or what I need to do to get it working?

Thanks

Jo

**Comment by fxprunayre** [comment]
I managed to have it more or less working with master in May but it was quite painful. Not sure it has been updated to work with current 3.8.x branch.

**Comment by stijngoedertier** [comment]
We updated the README.md file in December that documents how to deploy the plugin in GeoNetwork 3.6.0.
The latest version in the master branch will work with GeoNetwork 3.8.x.
